# WARNING:
# Do not use this file as is! It only lists and documents available options
# without caring about their consistency.

# The directory where models and summaries will be saved. It is created if it does not exist.
#model_dir: ../output/recom_nlg_emb
model_dir: ../onmt-tf-output/recom_nlg_clothes_t2t/layer2-unit256-head8-ffn1024_eof/

data:
  # (required for train_and_eval and train run types).
  train_features_file:
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/recom_text.words.train.filter.seg_new
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/recom_text.tags.train.filter.seg_new
  train_labels_file: ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/eof/recom_text.outs.train.seg_new.punctrmd.eof

  # (required for train_end_eval and eval run types).
  eval_features_file:
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/recom_text.words.val.filter.seg_new
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/recom_text.words.val.filter.seg_new
  eval_labels_file: ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/eof/recom_text.outs.val.seg_new.punctrmd.eof

  # (optional) Models may require additional resource files (e.g. vocabularies).
  source_words_vocabulary: data/recom_nlg/clothes/one_per_sku/words-outs-train.vocab
  feature_vocabulary: data/recom_nlg/clothes/one_per_sku/tags-train.vocab
  target_words_vocabulary: data/recom_nlg/clothes/one_per_sku/words-outs-train.vocab

params:
  beam_width: 1


