# WARNING:
# Do not use this file as is! It only lists and documents available options
# without caring about their consistency.

# The directory where models and summaries will be saved. It is created if it does not exist.
#model_dir: ../output/recom_nlg_emb
model_dir: ../onmt-tf-output/temp

data:
  # (required for train_and_eval and train run types).
  train_features_file: [../recom_nlg/temp/recom_text.words.train, ../recom_nlg/temp/recom_text.tags.train]
  train_labels_file: ../recom_nlg/temp/recom_text.outs.train

  # (required for train_end_eval and eval run types).
  eval_features_file: [../recom_nlg/temp/recom_text.words.val, ../recom_nlg/temp/recom_text.tags.val]
  eval_labels_file: ../recom_nlg/temp/recom_text.outs.val

  # (optional) Models may require additional resource files (e.g. vocabularies).
  source_words_vocabulary: data/recom_nlg/clothes/one_per_sku/words-outs-train.vocab
  feature_vocabulary: data/recom_nlg/clothes/one_per_sku/tags-train.vocab
  target_words_vocabulary: data/recom_nlg/clothes/one_per_sku/words-outs-train.vocab

  words_embedding: ../recom_nlg/temp/emb.vec

train:
  save_checkpoints_steps: 2
  save_summary_steps: 2
  train_steps: 4

eval:
  # (optional) Evaluate every this many seconds (default: 18000).
  eval_delay: 30

params:
  beam_width: 1


