# WARNING:
# Do not use this file as is! It only lists and documents available options
# without caring about their consistency.
#
# The directory where models and summaries will be saved. It is created if it does not exist.
model_dir: ../onmt-tf-output/temp

data:
  # (required for train_and_eval and train run types).
  train_features_file:
  - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/100/recom_text.words.train.filter.seg_new.top100
  - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/100/recom_text.tags.train.filter.seg_new.top100
  train_labels_file:
  - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/100/recom_text.outs.train.seg_new.attr_one.top100
  - - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/prefix_first_word/100/recom_text.outs.train.seg_new.punctrmd.shifted.1.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/prefix_first_word/100/recom_text.outs.train.seg_new.punctrmd.shifted.2.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/prefix_first_word/100/recom_text.outs.train.seg_new.punctrmd.shifted.3.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/prefix_first_word/100/recom_text.outs.train.seg_new.punctrmd.shifted.4.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/prefix_first_word/100/recom_text.outs.train.seg_new.punctrmd.shifted.5.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/prefix_first_word/100/recom_text.outs.train.seg_new.punctrmd.shifted.6.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/prefix_first_word/100/recom_text.outs.train.seg_new.punctrmd.shifted.7.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/prefix_first_word/100/recom_text.outs.train.seg_new.punctrmd.shifted.8.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/train/prefix_first_word/100/recom_text.outs.train.seg_new.punctrmd.shifted.9.top100

  # (required for train_end_eval and eval run types).
  eval_features_file:
  - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/100/recom_text.words.val.filter.seg_new.top100
  - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/100/recom_text.tags.val.filter.seg_new.top100
  eval_labels_file:
  - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/100/recom_text.outs.val.seg_new.attr_one.top100
  - - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/prefix_first_word/100/recom_text.outs.val.seg_new.punctrmd.shifted.1.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/prefix_first_word/100/recom_text.outs.val.seg_new.punctrmd.shifted.2.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/prefix_first_word/100/recom_text.outs.val.seg_new.punctrmd.shifted.3.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/prefix_first_word/100/recom_text.outs.val.seg_new.punctrmd.shifted.4.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/prefix_first_word/100/recom_text.outs.val.seg_new.punctrmd.shifted.5.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/prefix_first_word/100/recom_text.outs.val.seg_new.punctrmd.shifted.6.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/prefix_first_word/100/recom_text.outs.val.seg_new.punctrmd.shifted.7.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/prefix_first_word/100/recom_text.outs.val.seg_new.punctrmd.shifted.8.top100
    - ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/prefix_first_word/100/recom_text.outs.val.seg_new.punctrmd.shifted.9.top100

  eval_labels_file_full: ../recom_nlg/onmt/clothes/one_per_sku/2nd_seg/val/100/recom_text.outs.val.seg_new.temp.top100

  # (optional) Models may require additional resource files (e.g. vocabularies).
  source_words_vocabulary: data/recom_nlg/clothes/one_per_sku/words-train.vocab
  feature_vocabulary: data/recom_nlg/clothes/one_per_sku/tags-train.vocab
  master_target_words_vocabulary: data/recom_nlg/clothes/one_per_sku/words-train.vocab
  sub_target_words_vocabulary: data/recom_nlg/clothes/one_per_sku/outs-train.vocab
#
  words_embedding: ../recom_nlg/temp/emb.vec

train:
  batch_size: 4
  save_checkpoints_steps: 1
  save_summary_steps: 1
  train_steps: 4
  # whether to profile run time trace
  # profile_hook: True
#
eval:
 # (optional) Evaluate every this many seconds (default: 18000).
  eval_delay: 10

params:
  # whether to turn on printing debug_ops in hooks
  debug: True
  beam_width: 1


